### GET ALL NOTES
GET http://34.101.234.115:300/notes
Connection: close


### CREATE NOTE
POST http://34.101.234.115:300/notes  
Content-Type: application/json
  
{
  "judul": "Test dari HTTP",
  "isi": "Ini isi catatan"
}


### UPDATE NOTE
PUT http://localhost:3000/notes/1
Content-Type: application/json

{
  "judul": "Update Judul",
  "isi": "Sudah diubah"
}


### DELETE NOTE
DELETE http://localhost:3000/notes/1